package p168;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;


import static org.prokys.p168.P168.convertToTitle;

public class P168Test {

    @ParameterizedTest
    @CsvSource({
            "1, A",
            "2, B",
            "3, C",
            "4, D",
            "5, E",
            "6, F",
            "7, G",
            "8, H",
            "9, I",
            "10, J",
            "11, K",
            "12, L",
            "13, M",
            "14, N",
            "15, O",
            "16, P",
            "17, Q",
            "18, R",
            "19, S",
            "20, T",
            "21, U",
            "22, V",
            "23, W",
            "24, X",
            "25, Y",
            "26, Z",
            "27, AA",
            "28, AB",
            "29, AC",
            "30, AD",
            "31, AE",
            "32, AF",
            "33, AG",
            "34, AH",
            "35, AI",
            "36, AJ",
            "37, AK",
            "38, AL",
            "39, AM",
            "40, AN",
            "41, AO",
            "42, AP",
            "43, AQ",
            "44, AR",
            "45, AS",
            "46, AT",
            "47, AU",
            "48, AV",
            "49, AW",
            "50, AX",
            "51, AY",
            "52, AZ",
            "53, BA",
            "54, BB",
            "55, BC",
            "56, BD",
            "57, BE",
            "58, BF",
            "59, BG",
            "60, BH",
            "61, BI",
            "62, BJ",
            "63, BK",
            "64, BL",
            "65, BM",
            "66, BN",
            "67, BO",
            "68, BP",
            "69, BQ",
            "70, BR",
            "71, BS",
            "72, BT",
            "73, BU",
            "74, BV",
            "75, BW",
            "76, BX",
            "77, BY",
            "78, BZ",
            "79, CA",
            "80, CB",
            "81, CC",
            "82, CD",
            "83, CE",
            "84, CF",
            "85, CG",
            "86, CH",
            "87, CI",
            "88, CJ",
            "89, CK",
            "90, CL",
            "91, CM",
            "92, CN",
            "93, CO",
            "94, CP",
            "95, CQ",
            "96, CR",
            "97, CS",
            "98, CT",
            "99, CU",
            "100, CV",
            "675, YY",
            "676, YZ",
            "677, ZA",
            "678, ZB",
            "679, ZC",
            "680, ZD",
            "681, ZE",
            "682, ZF",
            "683, ZG",
            "684, ZH",
            "685, ZI",
            "686, ZJ",
            "687, ZK",
            "688, ZL",
            "689, ZM",
            "690, ZN",
            "691, ZO",
            "692, ZP",
            "693, ZQ",
            "694, ZR",
            "695, ZS",
            "696, ZT",
            "697, ZU",
            "698, ZV",
            "699, ZW",
            "700, ZX",
            "701, ZY",
            "702, ZZ",
            "703, AAA",
            "704, AAB",
            "705, AAC",
            "999, ALK",
            "1000, ALL",
            "17575, YYY",
            "17576, YYZ",
            "2147483645, FXSHRXU",
            "2147483646, FXSHRXV",
            "2147483647, FXSHRXW"

    })

    public void testDivide(int val, String result){
        Assertions.assertEquals(result, convertToTitle(val));
    }
}
